# Generated by Django 5.0.5 on 2024-05-08 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='first_name',
            new_name='biz_name',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='last_name',
            new_name='full_name',
        ),
        migrations.AddField(
            model_name='record',
            name='category',
            field=models.CharField(choices=[('prospect', 'prospect'), ('lead', 'lead'), ('customer', 'customer')], default='prospect', max_length=50),
        ),
    ]
