# Generated by Django 5.0.5 on 2024-05-08 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_first_name_record_biz_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='notes',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
