# Generated by Django 5.0.5 on 2024-05-08 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_record_notes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='notes',
            new_name='todos',
        ),
    ]
