# Generated by Django 5.0.5 on 2024-05-30 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_notes_record_todos'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
