# Generated by Django 5.0.5 on 2024-05-30 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_record_due_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='record',
            name='todos',
        ),
        migrations.CreateModel(
            name='Todos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todos', models.TextField(blank=True, max_length=1000, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.record')),
            ],
        ),
    ]
