# Generated by Django 5.0.5 on 2024-05-30 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_record_due_date_remove_record_todos_todos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todos',
            name='user',
        ),
        migrations.AddField(
            model_name='todos',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
