# Generated by Django 5.0.5 on 2024-05-31 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_todos_user_todos_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_date', models.DateTimeField(auto_now_add=True)),
                ('interaction_type', models.CharField(choices=[('email', 'email'), ('phone', 'phone'), ('meeting', 'meeting')], default='email', max_length=100)),
                ('notes', models.CharField(max_length=255)),
                ('follow_up', models.CharField(max_length=255)),
                ('client_id', models.IntegerField()),
            ],
        ),
    ]
