# Generated by Django 5.0.5 on 2024-05-31 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_interaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='interaction_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
