# Generated by Django 5.0.5 on 2024-05-31 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_interaction_interaction_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField(auto_now_add=True)),
                ('client_id', models.IntegerField()),
                ('service', models.CharField(max_length=100)),
                ('amount', models.FloatField()),
            ],
        ),
    ]
